baseURL = 'https://valourinpride.github.io/'
languageCode = 'en-us'
title = 'Valour In Pride'
theme = "blist"
contentDir = "content"
# weight = 1
# DefaultContentLanguage = "en"
# DefaultContentLanguageInSubdir = false

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]
  # Custom copyright - optional
  copyright = "© ∆ Valour In Pride"
  favicon = "/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  introTitle = "Valour In Pride "
  introSubtitle = "< Akhand Bharat  >"
  introPhoto = "/valourinpride.png"

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  logo = "/favicon.png"
[[menu.main]]
  name = "Blog" 
  url = "/blog"
  weight = 1
[[menu.main]]
  name = "About" 
  url = "/about-us"
  weight = 2
[[menu.main]]
  name = "Contact Us" 
  url = "/contact-us"
  weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]
